language: csharp
solution: Microsoft.CSharp.Extensions.sln

before_install:
  - nuget install nunit-console

before_script:
  - nuget restore Microsoft.CSharp.Extensions.sln
  
script:
  - xbuild /p:Configuration=Release Microsoft.CSharp.Extensions.sln

after_script:
  - nunit-console ./Microsoft.CSharp.Extensions.Tests/bin/Release/Microsoft.CSharp.Extensions.Tests.dll
