before_build:
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - nuget restore

build_script:
   - msbuild /p:Configuration=Release CSharp.ExtensionMethods.sln
 
test_script:
 .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\testrunner\NUnit.ConsoleRunner.3.7.0\tools/\nunit3-console.exe" -targetargs:".\CSharp.ExtensionMethods.Tests\bin\Release\CSharp.ExtensionMethods.Tests.dll" -output:".\coverage.xml" -filter:"+[CSharp.ExtensionMethods*]* -[CSharp.ExtensionMethods.Tests*]*"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 2ff19a3a-b268-4d5c-b78a-47f2aed1448e